/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef nydbc_CONSTANTS_H
#define nydbc_CONSTANTS_H

#include "nydbc_types.h"

namespace com { namespace yealink { namespace dbc { namespace idl {

class nydbcConstants {
 public:
  nydbcConstants();

};

extern const nydbcConstants g_nydbc_constants;

}}}} // namespace

#endif
